image: golang:latest

stages:
  - build
  - verify
  - test

build-job:
  stage: build
  script:
    - go mod download
    - go mod tidy
    - go build .

verify-job:
  stage: verify
  image: golangci/golangci-lint:latest
  allow_failure: false
  script:
    - golangci-lint run -v

test-job:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)