image: golang:latest

stages:
  - build
  - verify
  - test

build-job:
  stage: build
  script:
    # download all dependencies declared in go.mod file.
    - go mod download
    # keeps only the used ones.
    - go mod tidy
    # builds the project
    - go build .

verify-job:
  stage: verify
  image: golangci/golangci-lint:latest
  allow_failure: false
  script:
    # golangci is a Go linters aggregator that statically tests the code. If it fails, the pipeline is stopped.
    - golangci-lint run -v

test-job:
  stage: test
  script:
    # go fmt formats source code.
    - go fmt
    # go vet examines source code and reports suspicious constructs.
    - go vet
    # go test tests code with provided test files.
    - go test