# latest image using golang
image: golang:latest

# Global cache paths
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH="$PATH:$HOME/go/bin/"
  cache:
    paths:
      - .go/pkg/mod/

# Stages definition
stages:
  - docs

docs-job:
  stage: docs
  extends: .go-cache
  script:
    - go install golang.org/x/tools/cmd/godoc@latest
    - godoc -http=:6060 & # Start the GoDoc server in the background
    - sleep 10  # Wait for a moment to ensure the GoDoc server fully starts
    - wget -O doc.html http://localhost:6060/pkg   # Generate the documentation and save it to public/doc.html
    - kill %1  # Stop the GoDoc server
